"""Change of column name

Revision ID: 47bfbc392264
Revises: 943735859dbb
Create Date: 2024-02-22 13:10:39.742505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47bfbc392264'
down_revision: Union[str, None] = '943735859dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supervisors', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'supervisors', ['trade'])
    op.drop_column('supervisors', 'contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supervisors', sa.Column('contact', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'supervisors', type_='unique')
    op.drop_column('supervisors', 'email')
    # ### end Alembic commands ###
